#!/bin/sh

TIME=$1
if [ -z $TIME ]; then
	echo "You should specify time"
	exit
fi
PATTERN="[0-9]\{1,2}:[0-9]\{2}"
RESULT=`(echo "$TIME" | grep '[0-9]\{1,2\}:[0-9]\{2\}')`
if [ -z $RESULT ]; then
	echo "Format should be HH:MM"
	exit
fi
DIR="Ringtones"
RINGTONE=`/bin/ls -1 "$DIR" | sort --random-sort | head -1`
if [ -z $RINGTONE ]; then
	echo "No ringtones found. Add some to Ringtones/ folder"
	exit
fi
FULL_PATH=$DIR/$RINGTONE
if [ ! -s "$FULL_PATH" ]; then
	echo File $FULLPATH not found
	exit
fi
NOW=`date +%s`
TARGET=`date --date="$RESULT" +%s`
DATE=`date --date="$RESULT" +"%T"`
DIFF=`expr $TARGET - $NOW`
if [ $DIFF -lt 0 ]; then
	TARGET=`date --date="tomorrow "$RESULT"" +%s`
	DATE=`date --date="tomorrow "$RESULT"" +"%D %T"`
	DIFF=`expr $TARGET - $NOW`
fi
echo Alarm set to $DATE
sleep $DIFF
./incVolume &
cvlc $FULL_PATH
